apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller-2
spec:
  replicas: 1
  selector:
    app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: a18abe2ce8c1f11e7b3300e8493b4ebc-459757964.us-east-1.elb.amazonaws.com 
          #valueFrom:
           # fieldRef:
            #  fieldPath: status.podIP
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zook2:2181
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "2000000"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://a18abe2ce8c1f11e7b3300e8493b4ebc-459757964.us-east-1.elb.amazonaws.com:9092"
      - name: zookeeper
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zook2
  labels:
    app: kafka2
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    protocol: TCP
  selector:
    app: kafka2
