apiVersion: v1
kind: ReplicationController
metadata:
  name: nifi
spec:
  replicas: 2
  selector:
    app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: kokyj93/nifi
        ports:
        - containerPort: 8080
          name: access
        - containerPort: 8081
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nifi
  labels:
    app: nifi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nifi.deploybytes.com.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: access
    targetPort: access
    protocol: TCP
  - port: 8081
    name: http
    targetPort: http
    protocol: TCP
  selector:
    app: nifi
